### ISSUE TITLE
Optional ANALYZE when move data

### ISSUE THREAD

**Issue by dturon** [keithf4/pg_partman#138] opened 2016-09-15 11:16 UTC
Hi,

i found one, maybe corner case issue. On our instance long time not ran partman_maintence() and parent table bloat to 40GB(our fault), when i try move old data process hang on ANALYZE $parent_table here:
https://github.com/keithf4/pg_partman/blob/master/sql/functions/create_partition_time.sql#L291
becouse option (p_analyze boolean DEFAULT true) can't be set in partition_data_time/id. I fix this with comment line in function and works fine for me. Thanks and have nice day!

David

**Comment by dturon** [comment] 2016-09-15 11:21
BTW i found this with autoexplain, very usefull tool:

**Comment by keithf4** [comment] 2016-09-15 14:14
Yeah, someone else pointed this out as well in https://github.com/keithf4/pg_partman/pull/137
I do plan on fixing this for the next version. Thanks!

**Comment by keithf4** [comment] 2016-09-23 18:31
The below Gist contains the next patch update for pg_partman and includes this fix. If you've got time, please test it out in the environment where you encountered the performance issue and let me know how it goes. It's not the final version, so please don't install it on your prod system yet. I'll hopefully have the update out next week sometime then.

https://gist.github.com/keithf4/e86bafa682f086ad90b67e2240281f7d

**Comment by keithf4** [comment] 2016-09-26 21:30
Please reply on the other issue that this is a duplicate of if you have any issues.

**Closed by keithf4** 2016-09-26 21:30 UTC
Labels: duplicate
