### ISSUE TITLE
Issue upgrading to 2.6.3

### ISSUE THREAD

**Issue by francoisbeaulieu** [keithf4/pg_partman#167] opened 2017-02-19 04:41 UTC
Hi, I'm attempting to upgrade pg_partman from 2.0.0 to 2.6.3 and I'm getting the following error:

=# ALTER EXTENSION pg_partman UPDATE TO '2.6.3';
ERROR:  cannot ALTER TABLE "part_config_sub" because it has pending trigger events

Any ideas what can cause this? Should I upgrade to an interim version first?

**Comment by keithf4** [comment] 2017-02-19 06:58
I downloaded the v2.0.0 release and tested installing it then upgrading to 2.6.3 and am not encountering this issue. This is with 9.6. What version of postgres are you running? Would it be possible for you to provide a dump of your partman config tables? It may have to do with the data in them.
```
keith@keith=# create extension pg_partman schema partman;
CREATE EXTENSION
Time: 200.125 ms
keith@keith=# \dx
                                                          List of installed extensions
          Name          | Version |   Schema   |                                           Description                                           
------------------------+---------+------------+-------------------------------------------------------------
 pg_partman             | 2.0.0   | partman    | Extension to manage partitioned tables by time or ID

keith@keith=# alter extension pg_partman update to '2.6.3';
ALTER EXTENSION
Time: 1342.225 ms
keith@keith=# \dx
                                                          List of installed extensions
          Name          | Version |   Schema   |                                           Description                                           
------------------------+---------+------------+-------------------------------------------------------------
 pg_partman             | 2.6.3   | partman    | Extension to manage partitioned tables by time or ID

```

**Comment by francoisbeaulieu** [comment] 2017-02-19 15:36
I'm running on pgsql 9.4.10. this might be because I'm actually  
running a patched version of 2.0.0 (see  
https://github.com/keithf4/pg_partman/issues/47).

\dx says I'm running 2.1.0, but I don't recall ever upgrading to that.

Here is my part_config table dump:

--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = partman, pg_catalog;

--
-- Data for Name: part_config; Type: TABLE DATA; Schema: partman;  
Owner: postgres
--

INSERT INTO part_config (parent_table, control, partition_type,  
partition_interval, constraint_cols, premake, inherit_fk, retention,  
retention_schema, retention_keep_table, retention_keep_index,  
datetime_string, use_run_maintenance, jobmon, undo_in_progress,  
sub_partition_set_full) VALUES ('public.cel', 'eventtime', 'time', '7  
days', NULL, 5, true, '53 weeks', NULL, false, true, 'IYYY"w"IW',  
true, true, false, false);
INSERT INTO part_config (parent_table, control, partition_type,  
partition_interval, constraint_cols, premake, inherit_fk, retention,  
retention_schema, retention_keep_table, retention_keep_index,  
datetime_string, use_run_maintenance, jobmon, undo_in_progress,  
sub_partition_set_full) VALUES ('public.cdr', 'calldate', 'time', '7  
days', NULL, 5, true, '53 weeks', NULL, false, true, 'IYYY"w"IW',  
true, true, false, false);


--
-- PostgreSQL database dump complete
--


-- 
-=Frank


Quoting Keith Fiske <notifications@github.com>:

**Comment by francoisbeaulieu** [comment] 2017-02-19 15:48
For some reason pg_dump won't dump part_config_sub and the table schemas.

Here is the content of part_config_sub:

 sub_parent | sub_partition_type | sub_control | sub_partition_interval | sub_constraint_cols | sub_premake | sub_inherit_fk | sub_retention | sub_retention_schema | sub_retention_keep_table | sub_retention_keep_index | sub_use_run_maintenance | sub_jobmon
------------+--------------------+-------------+------------------------+---------------------+-------------+----------------+---------------+----------------------+--------------------------+--------------------------+-------------------------+------------
 public.cdr | time               | calldate    | daily                  |                     |           7 | t              |               |                      | t                        | t                        | t                       | t
 public.cel | time               | eventtime   | daily                  |                     |           7 | t              |               |                      | t                        | t                        | t                       | t
(2 rows)


Also, I don't know if this has any impact, but I had also just upgraded pg_jobmon from 1.3.0 to 1.3.2.

**Comment by keithf4** [comment] 2017-02-21 22:58
You must have 2.1.0 installed because the `sub_partition_set_full` column was not added until that version and it's contained in your `part_config` dump. Still not seeing the issue crop up and I'm using postgresql 9.4 as well (see below).

Googling around for that specific error shows it happens in circumstances where a constraint is altered in the same transaction that rows it affects are edited. Don't see any cases of that jumping out in pg_partman updates but with the gap of versions you're jumping between, there's certainly something I may have missed since all those updates are run in a single transaction. Me not being able to reproduce it, though, makes it hard to confirm that's the case.

Not sure what you may have done with installing a custom patch on the system. All I can suggest is trying to update to each interim version one at a time between 2.1.0 and 2.6.3 and see which one it fails at. That avoids doing all the updates in a single transaction and may avoid the issue. 

If you did the normal update to 2.1.0, that should have overrwritten the custom patch I'd made for you in Issue #47 and included the fix. Otherwise, I'm really not sure what the problem is.
```
$ psql
Expanded display is used automatically.

Current Host Server Date Time : Tue Feb 21 17:44:32 EST 2017 

psql (9.4.11)
Type "help" for help.

keith@keith=# create extension pg_partman schema partman;
CREATE EXTENSION
Time: 105.011 ms

keith@keith=# \dx
                               List of installed extensions
    Name    | Version |   Schema   |                     Description                      
------------+---------+------------+------------------------------------------------------
 pg_partman | 2.1.0   | partman    | Extension to manage partitioned tables by time or ID
 pgtap      | 0.95.0  | public     | Unit testing for PostgreSQL
 plpgsql    | 1.0     | pg_catalog | PL/pgSQL procedural language
(3 rows)

keith@keith=# INSERT INTO partman.part_config (parent_table, control, partition_type, partition_interval, constraint_cols, premake, inherit_fk, retention, retention_schema, retention_keep_table, retention_keep_index, datetime_string, use_run_maintenance, jobmon, undo_in_progress, sub_partition_set_full) VALUES ('public.cel', 'eventtime', 'time', '7 days', NULL, 5, true, '53 weeks', NULL, false, true, 'IYYY"w"IW', true, true, false, false); 
INSERT 0 1
Time: 5.843 ms
keith@keith=# 
keith@keith=# INSERT INTO partman.part_config (parent_table, control, partition_type, partition_interval, constraint_cols, premake, inherit_fk, retention, retention_schema, retention_keep_table, retention_keep_index, datetime_string, use_run_maintenance, jobmon, undo_in_progress, sub_partition_set_full) VALUES ('public.cdr', 'calldate', 'time', '7 days', NULL, 5, true, '53 weeks', NULL, false, true, 'IYYY"w"IW', true, true, false, false);
INSERT 0 1
Time: 3.065 ms

keith@keith=# select * from partman.part_config;
-[ RECORD 1 ]----------+-----------
parent_table           | public.cel
control                | eventtime
partition_type         | time
partition_interval     | 7 days
constraint_cols        | «NULL»
premake                | 5
inherit_fk             | t
retention              | 53 weeks
retention_schema       | «NULL»
retention_keep_table   | f
retention_keep_index   | t
datetime_string        | IYYY"w"IW
use_run_maintenance    | t
jobmon                 | t
sub_partition_set_full | f
undo_in_progress       | f
-[ RECORD 2 ]----------+-----------
parent_table           | public.cdr
control                | calldate
partition_type         | time
partition_interval     | 7 days
constraint_cols        | «NULL»
premake                | 5
inherit_fk             | t
retention              | 53 weeks
retention_schema       | «NULL»
retention_keep_table   | f
retention_keep_index   | t
datetime_string        | IYYY"w"IW
use_run_maintenance    | t
jobmon                 | t
sub_partition_set_full | f
undo_in_progress       | f

keith@keith=# alter extension pg_partman update to '2.6.3';
ALTER EXTENSION
Time: 517.792 ms
```

**Comment by francoisbeaulieu** [comment] 2017-02-22 00:10
It breaks on the upgrade from 2.6.2 to 2.6.3, with the same error message.

**Comment by keithf4** [comment] 2017-02-22 03:16
Can you dump out the part_config and part_config_sub table data again after upgrading to 2.6.2? That should work for the sub table now that you're up to date.

**Comment by francoisbeaulieu** [comment] 2017-02-22 04:03
Here you go!

[partman.dump.zip](https://github.com/keithf4/pg_partman/files/792196/partman.dump.zip)

I notice that there are 2 subpartitions now shown in part_config. That's strange because I undid my subpartitioning scheme last week using undo_partition.py. Why would the background worker create new ones? Could this be related? I re-ran undo_partition.py for the two partitions that appeared, but I still can't apply 2.6.3.

**Comment by keithf4** [comment] 2017-02-22 19:40
Maintenance will never add an entry into `part_config_sub`. Only calling `create_sub_parent()` does that. Maintenance only adds entries into `part_config` when subpartitioning creates new child tables that are themselves parents.

Sorry, to ask this again, but can you do the dump with the `--column-inserts` option? One mistake I made in the past was trying to re-order the columns in the tables.sql file whenever I'd add a new one. This can cause an issue if you ever have to dump/restore the config tables between upgrades and I mention that in the README. https://github.com/keithf4/pg_partman#upgrade

This shouldn't the cause of the issue you're seeing, though. Looking at the 2.6.3 update, I do edit a column and add a constraint on it at the same time, but I'm not triggering the issue myself when testing. Wondering if it's something the `part_config_sub` table.

**Comment by francoisbeaulieu** [comment] 2017-02-22 21:19
Ok, here's the new dump:

[partman.dump2.zip](https://github.com/keithf4/pg_partman/files/794815/partman.dump2.zip)

In regards to the maintenance job, that's what I meant: It added two new entries in part_config for partitions that had subpartitions. It also actually created said subpartitions. That makes no sense though, since I removed my subpartitioning scheme last week and only kept 1 level of partitions.

**Comment by keithf4** [comment] 2017-02-22 21:41
Not sure what happened then. Perhaps unpartitioning didn't finish completely? That's what happened to this person https://github.com/keithf4/pg_partman/issues/165#issuecomment-280052712

Was able to reproduce the issue now. Looks like I'll have to include some special instructions for updating to 2.6.3 when this issue is encountered. I'll let you know what they are once I figure it out.
```
keith@keith=# create extension pg_partman schema partman;
CREATE EXTENSION
Time: 180.439 ms
keith@keith=# \dx
                               List of installed extensions
    Name    | Version |   Schema   |                     Description                      
------------+---------+------------+------------------------------------------------------
 pg_partman | 2.6.2   | partman    | Extension to manage partitioned tables by time or ID
 pgtap      | 0.95.0  | public     | Unit testing for PostgreSQL
 plpgsql    | 1.0     | pg_catalog | PL/pgSQL procedural language
(3 rows)

keith@keith=# SET search_path = partman, pg_catalog;
SET
Time: 1.270 ms
keith@keith=# INSERT INTO part_config (parent_table, control, partition_type, partition_interval, constraint_cols, premake, inherit_fk, retention, retention_schema, retention_keep_table, retention_keep_index, datetime_string, use_run_maintenance, jobmon, undo_in_progress, sub_partition_set_full, epoch, optimize_trigger, optimize_constraint, infinite_time_partitions, trigger_exception_handling, upsert, trigger_return_null) VALUES ('public.cel', 'eventtime', 'time', '7 days', NULL, 5, true, '53 weeks', NULL, false, true, 'IYYY"w"IW', true, true, false, false, false, 5, 5, false, false, '', true);
INSERT 0 1
Time: 9.094 ms
keith@keith=# INSERT INTO part_config (parent_table, control, partition_type, partition_interval, constraint_cols, premake, inherit_fk, retention, retention_schema, retention_keep_table, retention_keep_index, datetime_string, use_run_maintenance, jobmon, undo_in_progress, sub_partition_set_full, epoch, optimize_trigger, optimize_constraint, infinite_time_partitions, trigger_exception_handling, upsert, trigger_return_null) VALUES ('public.cdr', 'calldate', 'time', '7 days', NULL, 5, true, '53 weeks', NULL, false, true, 'IYYY"w"IW', true, true, false, false, false, 5, 5, false, false, '', true);
INSERT 0 1
Time: 3.756 ms
keith@keith=# INSERT INTO part_config_sub (sub_parent, sub_partition_type, sub_control, sub_partition_interval, sub_constraint_cols, sub_premake, sub_inherit_fk, sub_retention, sub_retention_schema, sub_retention_keep_table, sub_retention_keep_index, sub_use_run_maintenance, sub_jobmon, sub_epoch, sub_optimize_trigger, sub_optimize_constraint, sub_infinite_time_partitions, sub_trigger_exception_handling, sub_upsert, sub_trigger_return_null) VALUES ('public.cdr', 'time', 'calldate', 'daily', NULL, 7, true, NULL, NULL, true, true, true, true, false, 7, 7, false, false, '', true);
INSERT 0 1
Time: 4.606 ms
keith@keith=# INSERT INTO part_config_sub (sub_parent, sub_partition_type, sub_control, sub_partition_interval, sub_constraint_cols, sub_premake, sub_inherit_fk, sub_retention, sub_retention_schema, sub_retention_keep_table, sub_retention_keep_index, sub_use_run_maintenance, sub_jobmon, sub_epoch, sub_optimize_trigger, sub_optimize_constraint, sub_infinite_time_partitions, sub_trigger_exception_handling, sub_upsert, sub_trigger_return_null) VALUES ('public.cel', 'time', 'eventtime', 'daily', NULL, 7, true, NULL, NULL, true, true, true, true, false, 7, 7, false, false, '', true);
INSERT 0 1
Time: 1.810 ms

keith@keith=# alter extension pg_partman update to '2.6.3';
ERROR:  cannot ALTER TABLE "part_config_sub" because it has pending trigger events
Time: 113.091 ms
```

**Comment by keithf4** [comment] 2017-02-23 22:04
So the best resolution I've found for this is to split the problem commands in 2.6.3 out into a new update to 2.6.4 and require these updates be installed in separate transactions. Below are two Gists with a new 2.6.3 update as well as the 2.6.4 update. Could you read the notes at the top of the 2.6.4 update, see if they make sense, apply the updates, then let me know if it works? Would be ideal if there's a way you could test this on a non-prod system just in case, but if not, this is the update I plan on rolling out publicly as long as there's no issues.  This should hopefully also work for people that already successfully updated to 2.6.3.

2.6.3 update - https://gist.github.com/keithf4/133c5924c8811c8be55834d0a15d0ef1
2.6.4 update - https://gist.github.com/keithf4/555223cb2d37fd81ff6a4fd5b310c667

**Comment by francoisbeaulieu** [comment] 2017-02-25 05:19
As the notes indicate, it worked when upgrading in steps, but failed when I first tried to upgrade straight to 2.6.4:

cdr=# ALTER EXTENSION pg_partman UPDATE TO '2.6.4';
ERROR:  cannot ALTER TABLE "part_config_sub" because it has pending trigger events
cdr=# ALTER EXTENSION pg_partman UPDATE TO '2.6.3';
ALTER EXTENSION
cdr=# ALTER EXTENSION pg_partman UPDATE TO '2.6.4';
ALTER EXTENSION

**Comment by keithf4** [comment] 2017-02-25 05:52
That's the intent. Thanks for confirming it worked for you! Will try to get 2.6.4 out soon.

**Comment by keithf4** [comment] 2017-02-27 18:40
Version 2.6.4 has been released with this fix.

Thanks again for reporting this and all your help debugging the issue!

**Comment by francoisbeaulieu** [comment] 2017-02-27 19:13
My pleasure! Thanks for the quick fix.

**Closed** 2017-04-10 19:19 UTC
Labels: confirmed bug, fixed in current release
