### ISSUE TITLE
Inserting into wrong table (constraint violation)

### ISSUE THREAD

**Issue by 1803** [keithf4/pg_partman#118] opened 2016-05-27 14:29 UTC
When initializing time-based partition from a remote session that has _timezone_ different from server  sub table constraints are created based on the start of partitioning period (e.g. month) for that time zone resulting in a bug for the sessions using different _timezone_.
Example:
I used JetBrains DataGrip for time-partitioning a table. DataGrip sets session timezone parameter to my local time zone (which is 'UTC+03:00'). My server, however has 'UTC+06:00' time zone.
Calling the following query:
`
select partman.create_parent('public.my_table', 'column_ts', 'time', 'monthly', p_premake => 12);
`
Results in creating 24 child tables each having the following constraints:

```
ALTER TABLE public.my_table_p2006_08
	ADD CONSTRAINT my_table_p2006_08_partition_check CHECK (column_ts >= '2006-08-01 02:00:00+06'::timestamp with time zone AND column_ts < '2006-09-01 02:00:00+06'::timestamp with time zone);
```
And as a result whenever a new entry has a _column_ts_ value in range 
`['2006-08-01 00:00:00+06', '2006-08-01 02:00:00+06')`
it causes constraint violation, because insert function puts the entry into p2006_08 child-table, however constraint expects it to be in p2006_07.

I believe using _timestamp_ instead of _timestamptz_ would solve this issue.

**Comment by keithf4** [comment] 2016-05-27 15:01
Assuming you closed this because you found the cause? Seems to me it's converting to the correct local time. 

Just want to make sure you got it figured out in case someone else asks the same question.

**Comment by 1803** [comment] 2016-05-31 08:51
Reopened after some additional testing.

**Comment by keithf4** [comment] 2016-05-31 14:18
The better solution for this is to ensure the client session has a timezone set to match whatever the server has. I have no way to predict which situation a person will need and it's much easier to work around it being a `timestamptz` than a `timestamp`.

**Comment by 1803** [comment] 2016-05-31 14:23
Turns out its not time zone. Its something else. I have same issue trying to deploy partitioning from server itself. Somehow it shifts timezone inside insert trigger function (adds 1 hour). Although its not very consistent. I'll make a new issue with fix if I figure it out.
Currently I suspect its because my table uses timestamptz and pg_partman functions mostly use timestamp except for trigger function.

**Comment by keithf4** [comment] 2016-05-31 14:25
Would be glad to look into it if you find the cause. Just ensure the clients, even local ones, are connecting with the same timezone as the server.

**Comment by 1803** [comment] 2016-05-31 14:37
Ok so... I figured out when it happens. 
Postgres automatically keeps track of any time zone standard changes. So when I was creating a wide range of partitions I was getting some tables for the times when Russia used DST (now Russia doesn't) so timestamp was getting shifted thus I was having +1 hour on timestamptz field in trigger function.
As for the fix.. I have no clue so far.

**Comment by keithf4** [comment] 2016-05-31 14:46
Yeah I've got no idea there. Maybe you can change the timezone settings for the client session to account for the differences of when that change went into affect.

Working with timezones just plain sucks unfortunately. 
https://www.youtube.com/watch?v=-5wpm-gesOY

**Comment by 1803** [comment] 2016-05-31 15:25
What I was really wondering about was "why doesn't check constraint use the same logic?". So I went ahead and changed all variables from timestamp to timestamptz in _create_partition_time_ function and it seems to work just fine. Constraint DDLs look good to me.
I guess the solution here is to stick to a single type, either timestamp or timestamptz, and as the guy on the video pointed out - leave it to those who are dealing with the problem since the begining.

**Comment by keithf4** [comment] 2016-05-31 16:04
Ok. I'll test things out and see if that has any other affects

**Comment by keithf4** [comment] 2016-06-24 15:34
In v2.4.0, I've gone through and changed all the time related data types to `timestamptz` in all functions to hopefully avoid this issue. As a side affect, this also allowed me to fix the issue in https://github.com/keithf4/pg_partman/issues/109 with epoch constraint exclusion. I was getting timezone mismatches between the epoch constraint and time constraint on the same table and this issue was behind it. So thanks for pointing this out and finding the underlying cause!

Let me know if you have anymore issues with this.

**Comment by 1803** [comment] 2016-06-28 08:34
I'm currently working on a solution for this as well.
I think that the best way to deal with time zone problem is to keep the initial time zone (the one that was set at the time of initialization of partition) in the `part_config` table and then convert all timestamps into that very time zone before generating any function code.
(this is supposed to solve issues for cases when partitioning is deployed in one time zone and then moved to another (we ship ready-to-go servers))

I will post an update as soon as I have more data on the topic.

**Comment by keithf4** [comment] 2016-06-28 13:38
If all the variables are timestamptz, that should solve issues encountered by the original poster. 

Moving the timezone of the entire server is an whole different issue. The only time I could see that realistically being handled to set a different timezone for the partition set is during the initial partition creation. Storing it as a config value doesn't seem very useful to me unless you need the partition set to remain different from the server timezone for the duration of its existence. But that doesn't seem to be your issue here and not sure I want to handle that at this time unless there's actual demand for it. If you changed the timezone at any time after any child tables are created, and the partition set needs to reflect that change, you'd have to update both the trigger functions and the constraints on every child table. Not sure I'm going to want to complicate pg_partman to handle such a rare edge case. 

My recommendation for your case of a deployable system would be to wait to run any create_parent() calls until your system is deployed to the designated timezone. If you already know what tables should be partitioned, that should be easily scriptable as something you can have your users run when they receive it. Or, if you already know the timezone of the location of the server beforehand, just set the timezone in the postgresql.conf file. Doing that would be far easier than trying to have pg_partman handle this and it's something you'd have to do anyway if you're pre-deploying postgres in a different timezone than it will run in later since that's set to the system timezone when initdb is called. 

If you have any trigger code suggestions, please post to this issue: https://github.com/keithf4/pg_partman/issues/42 
I already have an idea of how I'd like to handle this, I just haven't had the time to work on it. But I'm always open to ideas. Thanks!

**Comment by 1803** [comment] 2016-07-01 07:42
> If all the variables are `timestamptz`, that should solve issues encountered by the original post.
It does solve the issue only if the client uses the same timezone as the one that was used during partition creation and the timestamp is withing `optimize trigger` range.
Otherwise it will cause some troubles sooner or later.
Here's a simple repro case:
`set timezone = 'Europe/Moscow'; -- you dont need this if your time zone is not MST

create schema partman; -- creating schema for partition manager ext.
create extension pg_partman schema partman; -- v. 2.4.

-- creating simple table
create table ptime(id bigint primary key, pt timestamptz not null);

-- partitioning on timestamptz field
select partman.create_parent('public.ptime', 'pt', 'time', 'monthly', p_premake => 20);

-- This part might be not very accurate, but I didn't find a better way to apply trigger optimization:

-- set trigger optimization low enough so we can test
update partman.part_config set optimize_trigger = 2 where parent_table = 'public.ptime';

-- apply trigger changes
select partman.create_function_time('public.ptime');

-- A client from a different time zone wants to insert:
set timezone = 'MST'; -- GMT -07:00
insert into ptime values (1, timestamptz'2014-12-31 23:00'); -- 2014-12-31 23:00 -07:00 is next month in GMT +03:00

--actual code is: v_partition_name := partman.check_name_length('ptime', to_char(v_partition_timestamp, 'YYYY_MM'), TRUE);
`

**Comment by keithf4** [comment] 2016-07-01 15:29
Not sure I'm following your scenario now. I understand your example any why it errors out, but you described this as something you're shipping to run at a client's location. Is your intention to run partitioning in a different timezone than your client's location? That sounds confusing and not sure that's something I really want to try and support at this time. If that's not your intention, then I described a better way of handling this in my previous post so partitioning matches the intended timezone in the end.

Also, as far as maintenance is concerned, you should never be running maintenance with a client session in a timezone different than what the server is running in. That's just asking for trouble. You can set the session timezone for the client appropriately to match the server.

**Comment by 1803** [comment] 2016-07-01 19:16
Yeah there's a lot of time zone related issues, but lets for now ignore the one with server-shipping since its not that important. As you mentioned it's possible to delay the partitioning until the point the timezone of the customer is known.

Last case I provided, however, is pretty common. When a client with different time zone connects it might mess things up.

Now that I think about it, there's an easier way to handle this, just by setting time zone for the trigger function using `set` keyword.

```
create function some_fnc()
  language plpgsql volatile
  returns void
  set timezone = 'MST' as
$body$
$body$;
```

Will test it first thing tomorrow morning.

**Comment by keithf4** [comment] 2016-07-01 19:46
As I've said for your last case, it's better to set the timezone for the client session vs trying to have pg_partman handle it. You even do that in your example. That is the default manner in which postgres works and changing that would be far more confusing IMO. For example, if someone does log in and change their session timezone, then pg_partman would override it and cause unexpected behavior that that client would have no way to change without editing trigger source.

If a client should always have a default timezone set that is different than the server, then they can either do that with a .psqlrc file or you can even set default config options per user within the database
```
keith@keith=# create role tester with login;
CREATE ROLE
Time: 5.508 ms
keith@keith=# alter role tester set timezone = 'MST';
ALTER ROLE
Time: 6.500 ms
keith@keith=# show timezone;
  TimeZone  
------------
 US/Eastern
(1 row)

Time: 0.323 ms
keith@keith=# \q

$ psql -U tester keith

tester@keith=> show timezone
keith-> ;
 TimeZone 
----------
 MST
(1 row)
```

**Closed** 2016-07-12 18:27 UTC
Labels: confirmed bug, fixed in current release
