### ISSUE TITLE
Time-based functions use timestamptz even if underlying data is timestamp without time zone

### ISSUE THREAD

**Issue by lucasmo** [keithf4/pg_partman#76] opened 2015-12-08 01:19 UTC
Hi again. We have a timestamp column that contains a time without timezone information. We don't want postgresql to manage this timezone information as the data we work with is very timezone sensitive. 

As such, we keep all our data in the database as a timestamp without time zone. However, it looks like all the trigger functions are forcing timezones, giving an implied meaning to the data that isn't there:

```sql
DECLARE
    v_count                 int;
    v_partition_name        text;
    v_partition_timestamp   timestamptz;
BEGIN 
IF TG_OP = 'INSERT' THEN 
    v_partition_timestamp := date_trunc('hour', NEW."timestamp");
    IF NEW."timestamp" >= '2015-12-07 16:00:00-08' AND NEW."timestamp" < '2015-12-07 17:00:00-08' THEN 
        INSERT INTO public.xxxx_p2015_12_07_1600 VALUES (NEW.*); 
    ELSIF NEW."timestamp" >= '2015-12-07 15:00:00-08' AND NEW."timestamp" < '2015-12-07 16:00:00-08' THEN 
        INSERT INTO public.xxxx_p2015_12_07_1500 VALUES (NEW.*); 
...
```
Is this intended behavior? I wouldn't mind trying to write a patch here.

**Comment by keithf4** [comment] 2015-12-08 01:32
I'd wondered if there would be any issues with this myself when I first wrote it, but timestamptz seemed to handle `timestamp without time zone` fine so far where I've used it. I've run this extension on a client's system that does not use timestamptz either, but the triggers have still worked as intended for several years now. Is this causing things to break for you in some way? Would want to understand how before working on any sort of patch.

**Comment by keithf4** [comment] 2016-01-03 15:36
Please let me know if this is causing any issues for you. If not I will be closing this issue in the near future.

**Comment by rdab** [comment] 2016-01-05 18:40
Hello,
I think the current implementation using time zone is ok. As long as the postgresql.conf timezone parameter and the session timezone are configured properly, using `timestamp with time zone` would always be a better solution than not. Even for those app where timezone is not important (and not handled at all because i.e. it's intended to be used for people in the same building) it won't harm the logic (as said, if postgresql.conf timezone reflect the building location)

@lucasmo:  If your data is "very timezone sensitive" why is a problem the way its currently done? Hope you have a plan for the issues it could lead you to.

**Closed** 2016-02-03 16:47 UTC
Labels: question
